
server:
  port: 8782
spring:
  application:
    name: service-distributed-config-client
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: distributed
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh




