
server:
  port: 8782
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: # 可以被压缩的类型
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩
spring:
  application:
    name: service-distributed-book
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: distributed
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh




