version: '3'
services:
  seata-server:
    image: seataio/seata-server
    container_name: seata-server
    ports:
      - '8091:8091'
  nacos:
    image: nacos/nacos-server
    container_name: nacos-server
    ports:
      - '8848:8848'