version: '3'
services:
  seata-server:
    image: seataio/seata-server
    container_name: seata-server
    ports:
      - '8091:8091'
  nacos-server:
    image: nacos/nacos-server
    container_name: nacos-server
    ports:
      - '8848:8848'
  mysql-zipkin:
#    image: mysql:5.7.32
    image: registry.cn-hangzhou.aliyuncs.com/zt_images/mysql-zipkin:latest
    container_name: mysql-zipkin
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: zipkin
      MYSQL_USER: zipkin
      MYSQL_PASSWORD: zipkin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .\mysql-server\db:/var/lib/mysql
    networks:
      - zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
      - MYSQL_DB=zipkin
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - MYSQL_HOST=mysql-zipkin
      - MYSQL_TCP_PORT=3306
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
    networks:
      - zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    depends_on:
      - mysql-zipkin

  dic:
    container_name: dic
    image: nginx
    ports:
      - '8989:8989'
    volumes:
      - .\config\zdy.conf:/etc/nginx/conf.d/zdy.conf
      - .\dic:/usr/share/nginx/dic
    networks:
      - elastic
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - ELASTICSEARCH_HOSTS="http://es01:9200"
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - es01
      - es02
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - .\plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - .\plugins:/usr/share/elasticsearch/plugins
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  elastic:
    driver: bridge
  zipkin:
    driver: bridge